services:
  - type: web
    name: transcribe-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python script.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10